services:
  app:
    image: 816069131609.dkr.ecr.ap-northeast-2.amazonaws.com/samadhi-api:latest
    deploy:
      resources:
        limits:
          memory: 512M
    container_name: samadhi-api
    restart: always
    env_file:
      - ./.env
    ports:
      - "8888:8888"
